name: Run Bots Daily

on:
  schedule:
    - cron: '*/5 * * * *'  # Teste para rodar a cada 5 minutos
  push:
    branches:
      - main

jobs:
  run_bots:
    runs-on: ubuntu-latest  # O job vai rodar no Ubuntu mais recente

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Define a versão do Python a ser usada

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python  # Instala o pacote mysql-connector-python
        pip install beautifulsoup4  # Instala o pacote beautifulsoup4
        pip install requests  # Instala o pacote requests (muito comum para bots)
        pip install pandas  # Instala o pacote pandas (se necessário para seu bot)
        pip install lxml  # Instala o lxml, necessário para BeautifulSoup em alguns casos
        pip install selenium  # Instala o selenium, se necessário para bots que interagem com o navegador

    - name: Run Bot ESF
      run: python bot_esf.py  # Executa o primeiro bot

    - name: Run Bot LIV
      run: python bot_liv.py  # Executa o segundo bot
