# .github/workflows/run_bots_daily.yml

name: Run Bots Daily

on:
  schedule:
    - cron: '0 15 * * *'  # Executa diariamente às 15h UTC
  push:
    branches:
      - main

jobs:
  run_bots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python
          pip install beautifulsoup4
          pip install requests
          pip install pandas
          pip install lxml
          pip install selenium

      - name: Run Bot ESF
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TABLE_EMPRESAS_ESF: ${{ secrets.TABLE_EMPRESAS_ESF }}
          TABLE_PONTUACAO_ESF: ${{ secrets.TABLE_PONTUACAO_ESF }}
        run: python esf.py

      - name: Run Bot LIV
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TABLE_EMPRESAS_LIV: ${{ secrets.TABLE_EMPRESAS_LIV }}
          TABLE_PONTUACAO_LIV: ${{ secrets.TABLE_PONTUACAO_LIV }}
        run: python liv.py

      - name: Run Bot Slid_liv
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TABLE_BANNERS_LIV: ${{ secrets.TABLE_BANNERS_LIV }}
        run: python slid_liv.py
