name: Run Bots Daily

on:
  schedule:
    - cron: '0 15 * * *'  # Executa a cada 24 horas, às 15h UTC
  push:
    branches:
      - main

jobs:
  run_bots:
    runs-on: ubuntu-latest  # O job vai rodar no Ubuntu mais recente

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Define a versão do Python a ser usada

    - name: Setup ChromeDriver
      uses: selenium-actions/setup-chromedriver@v1
      with:
        chrome-version: '114.0.0'  # Substitua pela versão do Chrome que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python
        pip install beautifulsoup4
        pip install selenium
        pip install python-dotenv

    - name: Run Bot Esfera
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        # Variáveis para a tabela do ESF
        TABLE_EMPRESAS_ESF: ${{ secrets.TABLE_EMPRESAS_ESF }}
      run: python linkesf.py  # Executa o bot Esfera
