name: Run Bots Daily

on:
  schedule:
    - cron: '0 15 * * *'  # Executa a cada 24 horas, às 15h UTC
  push:
    branches:
      - main

jobs:
  run_bots:
    runs-on: ubuntu-latest  # O job vai rodar no Ubuntu mais recente

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Define a versão do Python a ser usada

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python
        pip install beautifulsoup4
        pip install requests
        pip install pandas
        pip install lxml
        pip install selenium

    - name: Run Bot ESF
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        # As variáveis para as tabelas do ESF
        TABLE_EMPRESAS_ESF: ${{ secrets.TABLE_EMPRESAS_ESF }}
        TABLE_PONTUACAO_ESF: ${{ secrets.TABLE_PONTUACAO_ESF }}
      run: python esf.py  # Executa o primeiro bot (Esfera).

    - name: Run Bot LIV
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        # As variáveis para as tabelas do LIV
        TABLE_EMPRESAS_LIV: ${{ secrets.TABLE_EMPRESAS_LIV }}
        TABLE_PONTUACAO_LIV: ${{ secrets.TABLE_PONTUACAO_LIV }}
      run: python liv.py  # Executa o segundo bot (Livelo).

    - name: Run Bot Slid_liv
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        # Se o script "slid_liv.py" também precisa usar as mesmas variáveis de tabelas da Livelo
        TABLE_EMPRESAS_LIV: ${{ secrets.TABLE_BANNERS_LIV }}
      run: python slid_liv.py  # Executa o terceiro bot (Slid Liv).
